const teamsImages = {
    "McLaren": "url_mclaren",
    "Mercedes": "url_mercedes",
    "Prost": "url_prost",
    "Sauber": "url_sauber",
    "Jordan": "url_jordan",
    "Williams": "url_williams",
    "BMW Sauber": "url_bmw_sauber",
    "Renault": "url_renault",
    "Minardi": "url_minardi",
    "Ferrari": "url_ferrari",
    "Alpine": "url_alpine",
    "Lotus": "url_lotus",
    "Caterham": "url_caterham",
    "Toro Rosso": "url_toro_rosso",
    "Alfa Romeo": "url_alfa_romeo",
    "Alfa Romeo Racing": "url_alfa_romeo_racing",
    "Toyota": "url_toyota",
    "Virgin": "url_virgin",
    "Marussia": "url_marussia",
    "BAR": "url_bar",
    "Super Aguri": "url_super_aguri",
    "Red Bull": "url_red_bull",
    "Spyker": "url_spyker",
    "Force India": "url_force_india",
    "Porsche": "url_porsche",
    "Mercedes AMG": "url_mercedes_amg",
    "Aston Martin": "url_aston_martin",
    "Benetton": "url_benetton",
    "Stewart": "url_stewart",
    "Honda": "url_honda",
    "Brawn": "url_brawn",
    "Joest Racing": "url_joest_racing",
    "Peugeot": "url_peugeot",
    "Midland": "url_midland",
    "Hispania": "url_hispania",
    "Jaguar": "url_jaguar",
    "HRT": "url_hrt",
    "Courage Compétition": "url_courage_competition",
    "DAMS": "url_dams",
    "Team Oreca": "url_team_oreca",
    "Pescarolo Sport": "url_pescarolo_sport",
    "Peugeot Total": "url_peugeot_total",
    "Arrows": "url_arrows",
    "Ligier": "url_ligier",
    "Simtek": "url_simtek",
    "Footwork": "url_footwork",
    "Tyrrell": "url_tyrrell",
    "Forti": "url_forti",
    "Italia": "url_italia",
    "Brabham": "url_brabham",
    "Lola": "url_lola",
    "Larrousse": "url_larrousse",
    "MasterCard Lola": "url_mastercard_lola",
    "Zakspeed": "url_zakspeed",
    "Pacific": "url_pacific",
    "AGS": "url_ags",
    "Coloni": "url_coloni",
    "EuroBrun": "url_eurobrun",
    "Andrea Moda": "url_andrea_moda",
    "Leyton House": "url_leyton_house",
    "March": "url_march",
    "Onyx": "url_onyx",
    "Rial": "url_rial",
    "Toleman": "url_toleman",
    "Osella": "url_osella",
    "Fondmetal": "url_fondmetal",
    "RAM": "url_ram",
    "Shadow": "url_shadow",
    "Modena": "url_modena",
    "ATS": "url_ats",
    "Ensign": "url_ensign",
    "Theodore": "url_theodore",
    "Spirit": "url_spirit",
    "Brabham y Onyx": "url_brabham_y_onyx",
    "Life": "url_life",
    "Haas": "url_haas",
    "Sauber y Caterham": "url_sauber_y_caterham",
    "Hesketh": "url_hesketh",
    "Haas Lola": "url_haas_lola",
    "Martini": "url_martini",
    "Surtees": "url_surtees",
    "Renault F1": "url_renault_f1",
    "Iso-Marlboro": "url_iso_marlboro",
    "Wolf": "url_wolf",
    "Fittipaldi": "url_fittipaldi",
    "Hill": "url_hill",
    "BRM": "url_brm",
    "Penske": "url_penske",
    "Boro": "url_boro",
    "Parnelli": "url_parnelli",
    "Rebaque": "url_rebaque",
    "Frank Williams Racing Cars": "url_frank_williams_racing_cars",
    "Brands Hatch": "url_brands_hatch",
    "Iso–Marlboro": "url_iso_marlboro",
    "Wolf–Williams": "url_wolf_williams",
    "Merzario": "url_merzario",
    "Kauhsen": "url_kauhsen",
    "Cooper": "url_cooper",
    "BS": "url_bs",
    "Penske & Shadow": "url_penske_and_shadow",
    "ShellSport": "url_shellsport",
    "Eifelland": "url_eifelland",
    "Maki": "url_maki",
    "Truesports": "url_truesports",
    "Kraco": "url_kraco",
    "Galles-Kraco": "url_galles_kraco",
    "Rahal-Hogan": "url_rahal_hogan",
    "Team Rahal": "url_team_rahal",
    "Gunston": "url_gunston",
    "Lexington": "url_lexington",
    "Token": "url_token",
    "Amon": "url_amon",
    "LEC": "url_lec",
    "McGuire": "url_mcguire",
    "Jolly Club": "url_jolly_club",
    "Heros Racing": "url_heros_racing",
    "Kojima": "url_kojima",
    "Reg Parnell": "url_reg_parnell",
    "Ian Raby": "url_ian_raby",
    "Matra": "url_matra",
    "Tecno": "url_tecno",
    "Wolf-Williams": "url_wolf_williams",
    "Mapfre": "url_mapfre",
    "Connew": "url_connew",
    "S.A.N": "url_san",
    "Lyncar": "url_lyncar",
    "Trojan": "url_trojan",
    "Scuderia Finotto": "url_scuderia_finotto",
    "AAW": "url_aaw",
    "Finotto": "url_finotto",
    "LDS": "url_lds",
    "Team Lotus": "url_team_lotus",
    "NART": "url_nart",
    "Rob Walker": "url_rob_walker",
    "Maserati": "url_maserati",
    "Centro Sud": "url_centro_sud",
    "Bonnier": "url_bonnier",
    "Bellasi": "url_bellasi",
    "Rob Walker Racing Team": "url_rob_walker_racing_team",
    "Eagle": "url_eagle",
    "De Tomaso": "url_de_tomaso",
    "Alfa Special": "url_alfa_special",
    "Reg Parnell Racing": "url_reg_parnell_racing",
    "Castrol": "url_castrol",
    "Anglo American Racers": "url_anglo_american_racers",
    "ENB": "url_enb",
    "UDT Laystall": "url_udt_laystall",
    "Scuderia Centro Sud": "url_scuderia_centro_sud",
    "DW Racing Enterprises": "url_dw_racing_enterprises",
    "Scuderia Ferrari": "url_scuderia_ferrari",
    "Scarab": "url_scarab",
    "Fry": "url_fry",
    "Protos": "url_protos",
    "Automobili Turismo e Sport": "url_automobili_turismo_e_sport",
    "North American Racing Team": "url_north_american_racing_team",
    "non-works BRM": "url_non_works_brm",
    "Bob Gerard Racing": "url_bob_gerard_racing",
    "Ace Garage": "url_ace_garage",
    "BRP": "url_brp",
    "Shannon": "url_shannon",
    "Yeoman": "url_yeoman",
    "Filipinetti": "url_filipinetti",
    "RE": "url_re",
    "Camoradi": "url_camoradi",
    "UDT": "url_udt",
    "Gilby": "url_gilby",
    "BMW": "url_bmw",
    "Gordini": "url_gordini",
    "Rosier": "url_rosier",
    "Vanwall": "url_vanwall",
    "Bugatti": "url_bugatti",
    "Serenissima": "url_serenissima",
    "Ecurie Maarsbergen": "url_ecurie_maarsbergen",
    "Scuderia Ugolini": "url_scuderia_ugolini",
    "EMW": "url_emw",
    "Derrington-Francis": "url_derrington_francis",
    "Scirocco": "url_scirocco",
    "Emeryson": "url_emeryson",
    "Stebro": "url_stebro",
    "Kurtis Kraft": "url_kurtis_kraft",
    "Lesovsky": "url_lesovsky",
    "Watson": "url_watson",
    "Bromme": "url_bromme",
    "Pawl": "url_pawl",
    "Kuzma": "url_kuzma",
    "Canadian Stebro Racing": "url_canadian_stebro_racing",
    "Veritas": "url_veritas",
    "Connaught": "url_connaught",
    "Porsche System Engineering": "url_porsche_system_engineering",
    "Racing Team Holland": "url_racing_team_holland",
    "Auguste Vaillet": "url_auguste_vaillet",
    "MZ": "url_mz",
    "MV Agusta": "url_mv_agusta",
    "Mercedes-Benz": "url_mercedes_benz",
    "HWM": "url_hwm",
    "JBW": "url_jbw",
    "Ferguson": "url_ferguson",
    "MBM": "url_mbm",
    "Benelli": "url_benelli",
    "Gilera": "url_gilera",
    "Norton": "url_norton",
    "NSU": "url_nsu",
    "Talbot-Lago": "url_talbot_lago",
};


module.exports = teamsImages;